### ISSUE TITLE
Links in installer file and documentation need updating

### ISSUE THREAD

**Issue by bookofthefuture** [home-assistant/hassio-installer#1]
Noticed that there is a stray /install/ in the links at the top of the hassio_install.sh file throughout, and in the readme below.

Plus the documentation on the main site needs updating to reflect the new repo location here:  https://www.home-assistant.io/hassio/installation/

**Comment by kabelux** [comment]
Getting 404 errors. Script trying to write a hassio-supervisor file, but curl can't reach the real content.

curl -sL ${URL_BIN_HASSIO} > /usr/sbin/hassio-supervisor
