### ISSUE TITLE
hassio installer not installing hassio but standard homeassistant

### ISSUE THREAD

**Issue by apat183** [home-assistant/hassio-installer#10]
Hi,

I'm following the instructions here to install hassio on my ubuntu server.
https://www.home-assistant.io/hassio/installation/#alternative-install-on-generic-linux-server

It installs fine and in docker I can see two containers, hassio_supervisor and homeassistant.

But when I go into home assistant it doesn't have any of the hassio tabs and addons etc. I thought installing it this way it installs a different homeassistant version that has all the addons? Am i missing something? 

Happy to provide any other details but I thought this is the way to install hassio?

**Comment by pvizeli** [comment]
Maybe a cache issue and you need clean up the browser cache?

**Comment by apat183** [comment]
Ok i'll try that out and report back, really hoping that is it since spent a couple of hours installing, clearing all docker items and reinstalling.

**Comment by superm1** [comment]
I would wonder if maybe you had stale data in `/usr/share/hassio` (default path used to store stuff)

**Comment by apat183** [comment]
It could have been, I tried to clear all data and search filesystem for anything "hass" related, I really think it was the browser cache. I ended up just installing home-assistant docker since I don't think I need most the plugins, and if I do I can just install the docker image and connect manually (e.g. influxdb or node-red etc).
