### ISSUE TITLE
Network manager isn't really needed

### ISSUE THREAD

**Issue by superm1** [home-assistant/hassio-installer#11]
The instructions at https://www.home-assistant.io/hassio/installation/ tell you to use network manager and https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh checks for it to be installed but as I can tell there isn't actually any usage for it.

**Comment by revolter** [comment]
Why is it still [mentioned as an optional package](https://www.home-assistant.io/hassio/installation/#debianubuntu), if it's not used?

**Comment by frenck** [comment]
It is used, to determine the upstream DNS server.

**Comment by revolter** [comment]
And could you please let me know what exactly does not work if you don't install it? I don't understand what "control your host network setup over the UI" refers to.
