### ISSUE TITLE
What could be the problem RPI3+ / [ERROR] Please set machine for armv7l

### ISSUE THREAD

**Issue by nardev** [home-assistant/hassio-installer#24]
I get this:
```
# curl -sL https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh | bash -s
[ERROR] Please set machine for armv7l
```

i have raspbian with latest kernel and running docker

```
Docker version 18.09.0, build 4d60db4
Linux raspberrypi 4.19.57-v7+ #1244 SMP Thu Jul 4 18:45:25 BST 2019 armv7l GNU/Linux
```

```
$ cat /etc/debian_version 
10.0
```

**Comment by JoeAstor** [comment]
Looks like i'm not the only one trying this :-)
Same error on my part

**Comment by nardev** [comment]
Well, i have just fount out that there is 

```
-m \| --machine |   | On a special platform they need set a machine type use
```

That helped some install, however, i have some network problems with it now. but the container looks to be running

**Comment by JoeAstor** [comment]
@nardev 
Thanks Man, worked like a charme..

![image](https://user-images.githubusercontent.com/50339032/61139936-bd6e9200-a4ca-11e9-8d17-764f3a07a923.png)

For everyone looking to get it to work.
This worked

curl -sL https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh | bash -s -- -m raspberrypi3

**Comment by frenck** [comment]
Glad you guys got it resolved. Closing issue.
