### ISSUE TITLE
Installing hass.io on TorizonCore

### ISSUE THREAD

**Issue by agners** [home-assistant/hassio-installer#25]
Hi,

I tried to install hass.io on TorizonCore on an Apalis iMX8. After making sure that my base system has the right tools pre-installed (jq and curl were missing), I was able to run the installer. However, it stopped pretty quickly:

```
# curl -sL https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh | bash -s -- -m qemuarm-64
[Warning] No AppArmor support on host.
mkdir: cannot create directory '/usr/share/hassio': Read-only file system
```

This is due to the nature that the base system is using OSTree which makes /usr Read-only. Is it possible to install the binaries to a different location (e.g. `/var`?). `/etc` is write able, so only the files stored in `/usr` are an issue.

**Comment by pvizeli** [comment]
You can modify the path with `-d /var/lib/hassio` -> https://github.com/home-assistant/hassio-installer#command-line-arguments

**Comment by agners** [comment]
I saw this, but from what I can see this only works for the data location, not for `hassio-supervisor` which gets installed to `/usr/sbin/hassio-supervisor`. I guess we could just add `-b` to specify a custom sbin dir?

**Comment by agners** [comment]
Not sure if I understand you correctly, but I did not plan to include them into the TorizonCore image by default since I plan to use the regular binary release which is also used for other applications.

I will create a pull request which allows to specify the installation directory.

**Comment by pvizeli** [comment]
Yeah, I was not sure if you would be faster for testing this with simple static files. Anyway, I'm all the time happy with improvements of that script :)
