### ISSUE TITLE
Script doesn't perform installation and doesn't give any feedback

### ISSUE THREAD

**Issue by Enkkfull** [home-assistant/hassio-installer#26]
So, I just installed raspbian buster on the raspberry 3b+ that I got about 3 hours ago. 

I had some troubles in installing docker because apparently there are issues with the containerd.io component shipped with the version of docker inside buster, which triggers an error `unable to find "net_prio" in controller set: unknown` on any image mounted on docker. Anyhow, I managed to fix it (apparently) since I was able to install Home Assistant without any further trouble. 

However, I wanted to install hass.io. So completely removed the home assistant container and all its files, I installed the dependencies for hass.io and I executed the script as reported on this github. 

I had no feedback and the script would instantly stop. After doing some careful reading of your script I discovered that it was able to create the config file (line 125) but it would not give me any echo on the docker installation (line 141). Therefore, the issue had to be in the DNS checking. 

```
# Check DNS settings
DOCKER_VERSION="$(docker --version | grep -Po "\d{2}\.\d{2}\.\d")"
if version_gt "18.09.0" "${DOCKER_VERSION}" && [ ! -e "$PREFIX/etc/docker/daemon.json" ]; then
    echo "[Warning] Create DNS settings for Docker to avoid systemd bug!"
    mkdir -p $PREFIX/etc/docker
    echo '{"dns": ["8.8.8.8", "8.8.4.4"]}' > $PREFIX/etc/docker/daemon.json

    echo "[Info] Restart Docker and wait 30 seconds"
    systemctl restart $DOCKER_SERVICE && sleep 30
fi
```

I downloaded the script and removed those lines and I got hass.io installed and (apprently) working seamingless. 

Now, I'm not really sure what the purpose of those lines was tho, so I'm asking here if I have to change manually some DNS configuration in order to avoid the "systemd bug" --I'm reading from the code-- , which I don't really know that it does. 

To avoid any trouble, I manually created the `/etc/docker/daemon.json` file and added that string. I don't know if I had to, my version is `Docker version 0.0.0-20190718010340-93c825c, build 93c825c` which I suppose is greater then `18.09.0` (that is the condition tested in the if).

In any case, it seemed like something to report to you. 

Thank you.

**Comment by cubilon** [comment]
+1

**Comment by jimloki** [comment]
Hi,

I'm on a fresh install of buster lite (RPi 3B). I have also a problem with the installer: nothing is installed and no feedback. /etc/hassio.json is not created

**Comment by Enkkfull** [comment]
> Hi,
> 
> I'm on a fresh install of buster lite (RPi 3B). I have also a problem with the installer: nothing is installed and no feedback. /etc/hassio.json is not created

In my case the hassio.json is created without any issue. Did you try to remove the portion of code I pointed out to see if it works?

**Comment by jimloki** [comment]
the portion you pointed out is after the creation of the file, that's why I didn't try that

**Comment by indomus** [comment]
Full (now) working guide (thanks to Enkfull btw) is there:

https://indomus.it/guide/come-installare-e-configurare-home-assistant-hassio-con-docker-su-un-raspberry-pi-gia-in-uso/

(you can translate in different languages using international flags placed on the top right corner of the page)
