### ISSUE TITLE
Preparing Hass.io .... infinite time

### ISSUE THREAD

**Issue by hippieua** [home-assistant/hassio-installer#31]
I've just tried to install hass.io on Hetzner Cloud (also tried to install on local vm)

after script finished with no error and [Info] Run Hass.io message, i can access web at http://ip.adrress:8123 but all i get is Preparing Hass.io (this can take up to 20 minutes) message.
Both VMs are fast and even after 4-5 hours there's nothing much happening.

OS: ubuntu-18.04.3-live-server-amd64, fresh install.  Docker-ce is installed as describes here: https://docs.docker.com/install/linux/docker-ce/debian/

have no clue what to do next.

**Comment by pvizeli** [comment]
Is fixed with supervisor 173. A restart or a new installation fix the issue
