### ISSUE TITLE
Install problem in aarch64 (Ubiquiti CloudKey G2-Plus)

### ISSUE THREAD

**Issue by anarro** [home-assistant/hassio-installer#33]
Hi, 

I have a Ubiquiti CloudKey-G2 Plus (a hardware with Debian and aarch64..), I like use this hardware with HA (hassio) and share it with the Ubiquiti applications (Unifi Network and Unifi Protect)...

First:
I was able to install the Docker service and configure it, then I ran the command (script) with specific parameter for machine type

> root@Cloud-Key-Gen2-Plus2:~# lsb_release -d
> Description:	Debian GNU/Linux 9.9 (stretch)

> root@Cloud-Key-Gen2-Plus2:~# cat /proc/cpuinfo 
> Processor	: AArch64 Processor rev 4 (aarch64)

> curl -sL https://raw.githubusercontent.com/home-assistant/hassioinstaller/master/hassio_install.sh | bash -s -- -m aarch64

but I have some problems when the service hassio-supervisor try download a docker image:

> Aug 17 02:52:38 Cloud-Key-Gen2-Plus2 hassio-supervisor[5674]: 19-08-17 00:52:38 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
Aug 17 02:52:38 Cloud-Key-Gen2-Plus2 hassio-supervisor[5674]: 19-08-17 00:52:38 INFO (MainThread) [hassio.host.services] Update service information
Aug 17 02:52:38 Cloud-Key-Gen2-Plus2 hassio-supervisor[5674]: 19-08-17 00:52:38 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
Aug 17 02:52:38 Cloud-Key-Gen2-Plus2 hassio-supervisor[5674]: 19-08-17 00:52:38 INFO (MainThread) [hassio.host.apparmor] Load AppArmor Profiles: set()
Aug 17 02:52:38 Cloud-Key-Gen2-Plus2 hassio-supervisor[5674]: 19-08-17 00:52:38 INFO (MainThread) [hassio.host.apparmor] AppArmor is not enabled on host
Aug 17 02:52:38 Cloud-Key-Gen2-Plus2 hassio-supervisor[5674]: 19-08-17 00:52:38 INFO (MainThread) [hassio.homeassistant] No Home Assistant Docker image homeassistant/aarch64-homeassistant found.
Aug 17 02:52:38 Cloud-Key-Gen2-Plus2 hassio-supervisor[5674]: 19-08-17 00:52:38 INFO (MainThread) [hassio.homeassistant] Setup HomeAssistant landingpage
Aug 17 02:52:38 Cloud-Key-Gen2-Plus2 hassio-supervisor[5674]: 19-08-17 00:52:38 INFO (SyncWorker_5) [hassio.docker.interface] Pull image homeassistant/aarch64-homeassistant tag landingpage.
Aug 17 02:52:40 Cloud-Key-Gen2-Plus2 hassio-supervisor[5674]: 19-08-17 00:52:40 ERROR (SyncWorker_5) [hassio.docker.interface] Can't install homeassistant/aarch64-homeassistant:landingpage -> 404 Client Error: Not Found ("manifest for homeassistant/aarch64-homeassistant:landingpage not found: manifest unknown: manifest unknown").
Aug 17 02:52:40 Cloud-Key-Gen2-Plus2 hassio-supervisor[5674]: 19-08-17 00:52:40 WARNING (MainThread) [hassio.homeassistant] Fails install landingpage, retry after 30sec

When the service try download a image.. : 

> **Pull image homeassistant/aarch64-homeassistant tag landingpage.
Aug 17 02:52:40 Cloud-Key-Gen2-Plus2 hassio-supervisor[5674]: 19-08-17 00:52:40 ERROR (SyncWorker_5) [hassio.docker.interface] Can't install homeassistant/aarch64-homeassistant:landingpage -> 404 Client Error: Not Found ("manifest for homeassistant/aarch64-homeassistant:landingpage not found: manifest unknown: manifest unknown").**

can someone help me?, please

**Comment by pvizeli** [comment]
https://github.com/home-assistant/hassio-installer#supported-machine-types

**Comment by anarro** [comment]
I'm sorry if I can't understand you Pascal,
but I read in a hassio_insall.sh this secction:

>
>ARCH=$(uname -m)
> .
> ..
> case $ARCH in
>   .
>   ..
>     "armv7l")
>         if [ -z $MACHINE ]; then
>             echo "[ERROR] Please set machine for $ARCH"
>             exit 1
>         fi
>         HOMEASSISTANT_DOCKER="$DOCKER_REPO/$MACHINE-homeassistant"
>         HASSIO_DOCKER="$DOCKER_REPO/armv7-hassio-supervisor"
>     ;;
>     **"aarch64")**
>         if [ -z $MACHINE ]; then
>             echo "[ERROR] Please set machine for $ARCH"
>             exit 1
>         fi
>         HOMEASSISTANT_DOCKER="$DOCKER_REPO/$MACHINE-homeassistant"
>         HASSIO_DOCKER="$DOCKER_REPO/aarch64-hassio-supervisor"
>     ;;
>     *)
>         echo "[Error] $ARCH unknown!"
>         exit 1
>     ;;
> esac
> ..
> .

and I understand that my "machine" it's supported...
I sorry for my ask..
