### ISSUE TITLE
Install fails on generic Ubuntu server 19.04, stuck on "Preparing Hass.io" screen

### ISSUE THREAD

**Issue by up2urheadlights** [home-assistant/hassio-installer#35]
I have installed 19.04 server on a generation 2 hyper-v VM.  I follow the install instruction for generic linux here:  https://www.home-assistant.io/hassio/installation/

Which pulls and installs this script.

When I browse to the instance at ipaddress:8123 I get the "Preparing Hass.io" screen, which never happens.

docker logs hassio_supervisor contains the following:

19-08-22 04:33:40 INFO (SyncWorker_4) [hassio.docker.interface] Pull image homeassistant/qemux86-64-homeassistant tag 0.97.2.
19-08-22 04:34:25 ERROR (SyncWorker_4) [hassio.docker.interface] Can't install homeassistant/qemux86-64-homeassistant:0.97.2 -> 404 Client Error: Not Found ("no such image: homeassistant/qemux86-64-homeassistant:0.97.2: No such image: homeassistant/qemux86-64-homeassistant:0.97.2").
19-08-22 04:34:25 WARNING (MainThread) [hassio.homeassistant] Error on install Home Assistant. Retry in 30sec

**Comment by up2urheadlights** [comment]
It turns out the problem was low disk space.  The Ubuntu Server 18.04 installer only allocates 4gb to the root partition if you use LVM option during install.  So the bug is in Ubuntu installer, not Hassio installer. I am going to leave this bug open though, as I believe the error in the log could be more descriptive of the actual problem.  The way it is now I was running around trying to figure out why I couldn't resolve the image, when in fact the installer could not extract the image due to low disk space.

**Comment by pvizeli** [comment]
Thanks for reporting. I will suggest using 18.04 as LT version if you want to use it as a server.
