### ISSUE TITLE
Machine type RPI4?

### ISSUE THREAD

**Issue by maximm07** [home-assistant/hassio-installer#38]
Hello, this is not an issue, more of a question..is install on RPI4 supported, because its missing under machine types? Can RPI3 be used? Thank you.

**Comment by surak** [comment]
It should be noted that the machine detection fails, and suggests an "armv7l", which will cause the landing page error as seen on the old repo: https://github.com/home-assistant/hassio-build/issues/58

**Comment by ENT108** [comment]
> It should be noted that the machine detection fails, and suggests an "armv7l", which will cause the landing page error as seen on the old repo: [home-assistant/hassio-build#58](https://github.com/home-assistant/hassio-build/issues/58)

So what machine type shall be put for rpi4? I am facing this issue...
