### ISSUE TITLE
Question about z-wave USB stick

### ISSUE THREAD

**Issue by hjkoster400d** [home-assistant/hassio-installer#40]
Hi there, thanks for the great script that saved me a lot of time setting up home assistant. Today i received my z-wave (Aeontec gen 5) usb stick and its connected at /dev/ttyACM0. But now i need to pass the --device /dev/ttyACM0 argument to the docker container but i have no idea how to do that. Can you help me out?

Thank you

Gr Rik

**Comment by pvizeli** [comment]
That is done automatic

**Comment by hjkoster400d** [comment]
Also when the stick is plugged in after installation?

**Comment by hjkoster400d** [comment]
It was working indeed out of the box, my fault :S
