### ISSUE TITLE
Uninstall instructions

### ISSUE THREAD

**Issue by hjkoster400d** [home-assistant/hassio-installer#42]
Hi there, 

I recently installed HA using your script on two machines, and now i'm wondering how i can remove the installation from the device. (docker images and containers, AppArmor, supervisor, etc..)

Is there an easy way to do this?

**Comment by pvizeli** [comment]
No easy way. Feel free to provide an uninstall script 👍

**Comment by hjkoster400d** [comment]
I used these commands to stop and remove the images and containers from the system:
#bin/bash

#remove images (also prevents from restarting containers)
docker image rm $(docker image ls -aq)

#stop containers
docker container stop $(docker container ls -aq)

#remove containers
docker container rm $(docker container ls -aq)

#uninstall packages
apt-get -y remove apparmor docker-ce

#cleanup some directories
....

**Comment by Saur0o0n** [comment]
Well it was too much to create uninstall script for "the team" :( - just make the mess on the system and don't even bother to report what was done.
This script also create system services, so you should stop and remove them also..
```
/usr# systemctl |grep hass
  sys-devices-virtual-net-hassio.device                                                                      loaded active plugged   /sys/devices/virtual/net/hassio                                                                 
  sys-subsystem-net-devices-hassio.device                                                                    loaded active plugged   /sys/subsystem/net/devices/hassio                                                               
  hassio-apparmor.service                                                                                    loaded active exited    Hass.io AppArmor                                                                                
  hassio-supervisor.service                                                                                  loaded active running   Hass.io supervisor                        
```
So first stop services, then remove containers as above.
Purge apparmor and docker (if you don't have running other containers).
```
aptitude purge apparmor docker.io
```

And then, there is still a lot of trash left to remove
```
/etc/hassio.json
/etc/systemd/system/hassio-apparmor.service
/etc/systemd/system/hassio-supervisor.service
/etc/systemd/system/multi-user.target.wants/hassio-apparmor.service
/etc/systemd/system/multi-user.target.wants/hassio-supervisor.service
/usr/sbin/hassio-apparmor
/usr/sbin/hassio-supervisor
```
and entire directory "/usr/share/hassio"

**Comment by frenck** [comment]
There is no need to put up that tone @Saur0o0n, and is actually against our code of conduct. Consider this a warning.

We are always open to contributions containing improvements or adding documentation. There was no need to do that negatively or with a tone.

The installation script is open source and not that big, doing the reverse should not be a problem for someone using that method.

Regarding your provided uninstall steps, "docker.io" should actually never been used in the first place; as it causes issues. So it is kinda weird to see it pop up in those steps.

**Comment by tripmine253** [comment]
I appreciate the feedback from the responding parties. I have to try this one final time.
