### ISSUE TITLE
Can't start Homeassistant container

### ISSUE THREAD

**Issue by germeraad** [home-assistant/hassio-installer#47]
Hi,

I’m having issues with a new install of hassio I’m using the install script (installer) to install on an Intel-NUC with Ubuntu 18.03 LTS. The hassio_supervisor and hassio_dns are running fine. The homeassistant container is created but during starting procedure from the supervisor I get the following issue:

> 19-09-30 12:36:30 ERROR (SyncWorker_5) [hassio.docker] Can’t start homeassistant: 500 Server Error: Internal Server Error (“OCI runtime create failed: sysctl “kernel.domainname” is not in a separate kernel namespace: unknown”),
> 19-09-30 12:36:30 ERROR (MainThread) [hassio.homeassistant] Can’t start Home Assistant!

**Comment by pvizeli** [comment]
> Error: Internal Server Error (“OCI runtime create failed: sysctl “kernel.domainname” is not in a separate kernel namespace: unknown”),

There is an issue with your kernel configs and docker setup
