### ISSUE TITLE
Can't install Hassio on Orange pi zero

### ISSUE THREAD

**Issue by thangtq19** [home-assistant/hassio-installer#5]
Hi Guys,

i have just learned about Hass for 2 weeks. And I bought an orange pi zero to build a hassio for me.
I found out a way to do and everything is good. But my hassio had error and i have to reinstall it again.
This is the way that i did.
_

> sudo -i
> add-apt-repository universe ( cái này thi thoảng nó báo lỗi cứ kệ nó đi :))
> apt-get update ( có ở trên rồi nhưng bấm lại cho chắc ;))
> apt-get install -y apparmor-utils apt-transport-https avahi-daemon ca-certificates curl dbus jq network-manager socat software-properties-common
> curl -fsSL get.docker.com | sh
> wget https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/hassio_install
> chmod u+x hassio_install
> ./hassio_install -m qemuarm

_

But this time. everything is not so easy. i met trouble when i did this step:
_wget https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/hassio_install_
the URL in this command line was died. i tried to look for the other way but still fail.
Could you all please help me?
Thanks

**Comment by bjakobs** [comment]
I think it has been replaced with https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh
