### ISSUE TITLE
How to update hassio?

### ISSUE THREAD

**Issue by hista** [home-assistant/hassio-installer#55]
Hi,
I've installed hassio on a raspbian by following this tutorial:https://github.com/home-assistant/hassio-installer

Now in the hassio log I get this message:
`Host has no rauc support. OTA updates have been disabled.`

How to update hassio which is running in docker-ce now?

Thanks for your kind help :-)

**Comment by hista** [comment]
Ok I think I've found by myself :)
https://i.imgur.com/7P29csB.png

**Comment by frenck** [comment]
Yep, that is how you update Home Assistant. Updates for Hass.io itself are handled automatically. For updating your host system, you should consult the manual of the operating system you've installed. On manual installations, that is your own responsibility.

**Comment by hista** [comment]
Thanks for your confirmation.
Yes to update my host system that's not a problem, it's debian-based (Raspbian) so I know the trick :)

**Comment by OddyAte** [comment]
Hey guys, I get the same message in the log but I do not have the 0.101.3 update in the Hass.IO tab
