### ISSUE TITLE
https://raw.githubusercontent.com not working

### ISSUE THREAD

**Issue by mochoandre** [home-assistant/hassio-installer#56]
It looks like https://raw.githubusercontent.com is not available anymore or temporaly unvailable.
It gives 
`curl -sL https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/hassio_install.sh | bash -s -- -m raspberrypi3   
bash: line 1: 404:: command not found`

**Comment by pvizeli** [comment]
mabye an outage on github
