### ISSUE TITLE
Only hassio_supervisor container is deployed

### ISSUE THREAD

**Issue by alesc** [home-assistant/hassio-installer#57]
On Raspberrypi3 with this command : 
`curl -sL "https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh" | bash -s -- -m raspberrypi3 -d /home/homeassistant/`

I only got this : 
`-> docker ps
CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS                       PORTS               NAMES
ccf94eb94ed9        homeassistant/armv7-hassio-supervisor   "/bin/entry.sh pytho…"   2 minutes ago       Up 2 minutes                                     hassio_supervisor
`

Nothing listen on 8123 and I can't understand in the shell script when home-assistant docker image sould be set up. 

Could you explain what's i'm doing wrong ?

**Comment by alesc** [comment]
DNS resolution was KO in hassio container .. I close this issue !

**Comment by tbrasser** [comment]
After you enable the hassio supervisor service, you should also start it (or reboot your device).
