### ISSUE TITLE
HA container log file too big

### ISSUE THREAD

**Issue by escoand** [home-assistant/hassio-installer#6]
I've installed Hass.io with the installer script to a ODROID-HC1 which is a stripped down XU4. This worked really well and the system is running fine.

But I realized a problem with the HA container filling all the SD card space with the container log file json.log. In it there is all the HA logging in debug level which is quiet much.

My quick'n'dirty solution was to link the file to /dev/null. Is there a better and consistent way?

**Comment by escoand** [comment]
Obviously is even more dirty than quick. Docker failed to restart the container with that link. So currently my only "solution" is to truncate the log from time to time.

**Comment by frenck** [comment]
When you run your own "general Linux" version, you have to maintain that yourself, this is out of scope for Home Assistant.

The answer here is to add max logging file sizes to your Docker configuration file (in `/etc/docker/daemon.json`).
