### ISSUE TITLE
CoreDNS not loading

### ISSUE THREAD

**Issue by nilsbraden** [home-assistant/hassio-installer#60]
Hello!

I'm trying to get things up and running on my Raspberry Pi 4 64bit 4GB with this installer script.

Locally configured and running services:
- ISC DHCP Server
- Pi-Hole DNS

Attaching to Hassio-Supervisor (**pi@raspi:~ $docker start --attach hassio_supervisor**) yields the following output over and over again:

```
19-11-27 12:40:21 INFO (MainThread) [hassio.dns] Start CoreDNS plugin
19-11-27 12:40:21 INFO (SyncWorker_17) [hassio.docker.interface] Clean hassio_dns application
19-11-27 12:40:24 INFO (SyncWorker_17) [hassio.docker.dns] Start DNS homeassistant/aarch64-hassio-dns with version 1
19-11-27 12:40:41 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with CoreDNS plugin!
19-11-27 12:40:41 WARNING (MainThread) [hassio.tasks] CoreDNS plugin is in fails state / Reset config
```

This plugin seems to be responsible for a lot of problems like updater not working, geolocalisation not working, several plugins can't access remote resources.

I'm stuck here. Can anybody point out where to look for further information on why exactly CoreDNS fails to load? I'm relatively new to Hassio and can't find any other logs providing insight.

Regards,
Nils

**Comment by pvizeli** [comment]
I think you have an DNS loop. That remember me to add the loop protection to CoreDNS to protect users for wrong setups

**Comment by nilsbraden** [comment]
I don't see how the setup can lead to a loop. 😕 

Pi-Hole has the router of my ISP configured as upstream dns server so any device asking Pi-Hole for a resolve should end up on some outside dns server. And docker per default uses the configuration of the host for all containers regarding DHCP and DNS config, right?

I tried nslookup within another docker container and it works.

**Comment by nilsbraden** [comment]
Hi @pvizeli! I'm still stuck here and don't know where to investigate further.

I tried reconfiguring my host with different DNS settings (external server, dhcp, fixed DNS in /etc/docker/daemon.json, disabling Pi-Hole, and a lot of other things including manually configuring coredata and editing dns.py). Nothing seemed to change anything about the behavior of coredns stopping without a meaningful error message.

Updating to 0.103.3 didn't change anything although I've seen some changes regarding DNS in hassio.

Do you have any other suggestions?

**Comment by William0702** [comment]
same problem here...

but on a rpi 3B

running:
HassOS 2.12
supp; 193
Home Assistant 0.103.5

any suggestions on what to do?

`20-01-04 22:12:20 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with CoreDNS plugin!
20-01-04 22:12:20 WARNING (MainThread) [hassio.tasks] CoreDNS plugin is in fails state / Reset config
20-01-04 22:12:20 INFO (MainThread) [hassio.dns] Start CoreDNS plugin
20-01-04 22:12:20 INFO (SyncWorker_12) [hassio.docker.interface] Clean hassio_dns application
20-01-04 22:12:32 INFO (SyncWorker_12) [hassio.docker.dns] Start DNS homeassistant/armv7-hassio-dns with version 1`

**Comment by jefmit01** [comment]
I am having the same issue.  

Any suggestions would be appreciated.

**Comment by pvizeli** [comment]
That means you have a DNS loop in your network

**Comment by DanielsWrath** [comment]
I've got the same problem on my raspberry pi 3
```Jan 08 12:51:29 raspberrypi hassio-supervisor[7927]: 20-01-08 12:51:29 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with CoreDNS plugin!
Jan 08 12:51:29 raspberrypi hassio-supervisor[7927]: 20-01-08 12:51:29 INFO (MainThread) [hassio.dns] Start CoreDNS plugin
Jan 08 12:51:29 raspberrypi hassio-supervisor[7927]: 20-01-08 12:51:29 ERROR (SyncWorker_18) [hassio.docker] Can't create container from hassio_dns: 404 Client Error: Not Found ("No such image: homeassistant/armv7-hassio-dns:1")
Jan 08 12:51:29 raspberrypi hassio-supervisor[7927]: 20-01-08 12:51:29 ERROR (MainThread) [hassio.dns] Can't start CoreDNS plugin
Jan 08 12:51:29 raspberrypi hassio-supervisor[7927]: 20-01-08 12:51:29 ERROR (MainThread) [hassio.tasks] Watchdog CoreDNS reanimation fails!
Jan 08 12:51:49 raspberrypi hassio-supervisor[7927]: 20-01-08 12:51:49 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with CoreDNS plugin!
Jan 08 12:51:49 raspberrypi hassio-supervisor[7927]: 20-01-08 12:51:49 INFO (MainThread) [hassio.dns] Start CoreDNS plugin
Jan 08 12:51:49 raspberrypi hassio-supervisor[7927]: 20-01-08 12:51:49 ERROR (SyncWorker_4) [hassio.docker] Can't create container from hassio_dns: 404 Client Error: Not Found ("No such image: homeassistant/armv7-hassio-dns:1")
Jan 08 12:51:49 raspberrypi hassio-supervisor[7927]: 20-01-08 12:51:49 ERROR (MainThread) [hassio.dns] Can't start CoreDNS plugin
Jan 08 12:51:49 raspberrypi hassio-supervisor[7927]: 20-01-08 12:51:49 ERROR (MainThread) [hassio.tasks] Watchdog CoreDNS reanimation fails!
Jan 08 12:52:09 raspberrypi hassio-supervisor[7927]: 20-01-08 12:52:09 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with CoreDNS plugin!
Jan 08 12:52:09 raspberrypi hassio-supervisor[7927]: 20-01-08 12:52:09 INFO (MainThread) [hassio.dns] Start CoreDNS plugin
Jan 08 12:52:09 raspberrypi hassio-supervisor[7927]: 20-01-08 12:52:09 ERROR (SyncWorker_10) [hassio.docker] Can't create container from hassio_dns: 404 Client Error: Not Found ("No such image: homeassistant/armv7-hassio-dns:1")
Jan 08 12:52:09 raspberrypi hassio-supervisor[7927]: 20-01-08 12:52:09 ERROR (MainThread) [hassio.dns] Can't start CoreDNS plugin
Jan 08 12:52:09 raspberrypi hassio-supervisor[7927]: 20-01-08 12:52:09 ERROR (MainThread) [hassio.tasks] Watchdog CoreDNS reanimation fails!
...
```
@pvizeli This is my output ```pi@raspberrypi:~ $ docker logs hassio_dns
Error: No such container: hassio_dns
```

**Comment by nilsbraden** [comment]
> That means you have a DNS loop in your network. What is the output of `docker logs hassio_dns`?

For me the output is always empty except during the short timeframe where the container is recreated, there it gives the error "No such container" of course. And the container is recreated about once every 20 seconds.

**Comment by Cloudenius** [comment]
Same here. I'm running Home Assistant 0.103.6 on HassOS 3.7 on a Raspberry Pi 4. It's using another Raspberry Pi running with HassOS 3.7 and the AdGuard add-on as a DNS server. I'm wondering how this can cause a DNS loop, because AdGuard is using Quad9.

**Comment by jefmit01** [comment]
I was able to clear the issue by doing a clean reinstall of Hassio/HA.  I am not sure what changed to cause the issue.  There were no changes to my network.  Problem arose after hassio/HA updates.   
On Saturday, January 11, 2020, 1:13 AM, Jean-Paul van Ravensberg <notifications@github.com> wrote:

Same here. I'm running Home Assistant 0.103.6 on HassOS 3.7 on a Raspberry Pi 4. It's using another Raspberry Pi running with HassOS 3.7 and the AdGuard add-on as a DNS server. I'm wondering how this can cause a DNS loop, because AdGuard is using Quad9.

**Comment by DanielsWrath** [comment]
@jefmit01 Yup, reinstalling worked for me as well! Solved somehow

**Comment by nilsbraden** [comment]
It's not solved for me, can nobody give any information on how to debug this DNS resolver of yours??
