### ISSUE TITLE
Cannot update hass.io

### ISSUE THREAD

**Issue by miroslavpetrov** [home-assistant/hassio-installer#63]
I use hassio installed on ubuntu server. I have been using it for more than 6 months and I have always updated the hass.io using the hass.io tab in home assistant. Now when I try to update from 0.102.3 to 0.103.0 I get this error:

`19-12-17 12:20:50 WARNING (MainThread) [hassio.homeassistant] Update Home Assistant image fails
19-12-17 12:20:51 INFO (MainThread) [hassio.homeassistant] Update Home Assistant to version 0.103.0
19-12-17 12:20:51 INFO (SyncWorker_1) [hassio.docker.interface] Update image homeassistant/qemux86-64-homeassistant:0.102.3 to homeassistant/qemux86-64-homeassistant:0.103.0
19-12-17 12:20:51 INFO (SyncWorker_1) [hassio.docker.interface] Pull image homeassistant/qemux86-64-homeassistant tag 0.103.0.
19-12-17 12:20:51 ERROR (SyncWorker_1) [hassio.docker.interface] Can't install homeassistant/qemux86-64-homeassistant:0.103.0 -> 500 Server Error: Internal Server Error ("Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.0.1:53: read udp 127.0.0.1:51901->127.0.0.1:53: read: connection refused").`

**Comment by frenck** [comment]
Look like you have changed something about your DNS on your main operating system, causing the DNS not to work inside Docker.

**Comment by pvizeli** [comment]
![image](https://user-images.githubusercontent.com/15338540/71009778-1631fe80-20eb-11ea-8207-51b22e735539.png)
