### ISSUE TITLE
Hassio fails to pull the raspberrypi3 image

### ISSUE THREAD

**Issue by robUx4** [home-assistant/hassio-installer#65]
I ran the following script as root (`sudo -i`):

> curl -sL "https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh" | bash -s -- -m raspberrypi3

The installation went well, but then Hassio doesn't show up. Looking at the logs it seems the raspberrypi3 image doesn't exist:
```
19-12-29 09:24:20 INFO (SyncWorker_9) [hassio.docker.interface] Pull image homeassistant/raspberrypi3-homeassistant tag landingpage.
19-12-29 09:24:23 ERROR (SyncWorker_9) [hassio.docker.interface] Can't install homeassistant/raspberrypi3-homeassistant:landingpage -> 404 Client Error: Not Found ("no such image: homeassistant/raspberrypi3-homeassistant:landingpage: No such image: homeassistant/raspberrypi3-homeassistant:landingpage").
19-12-29 09:24:23 WARNING (MainThread) [hassio.homeassistant] Fails install landingpage, retry after 30sec
```

**Comment by maximus5684** [comment]
The image definitely exists: https://hub.docker.com/r/homeassistant/raspberrypi3-homeassistant/tags?page=1&name=land

Verify that you can access the Internet from the Raspberry Pi with something like `ping 8.8.8.8`.

**Comment by marcelorodpinheiro** [comment]
I have the same problem and It's not internet access as I'm writing this comment from my pi3B+.
Seems to be something related to the upload of the image and the command "docker login".

`root@raspberrypi:/home/pi/Downloads# docker pull homeassistant/armv7-hassio-homeassistant:195
Error response from daemon: pull access denied for homeassistant/armv7-hassio-homeassistant, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

**Comment by pvizeli** [comment]
Fix with the latest commit they validate the user input
