### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by svh1985** [home-assistant/hassio-installer#67]
I've tried to run the script on my Mac to get it running in Docker but I got:
`[Error] Only systemd is supported!`

Is there a way of getting it to work on macOS?

**Comment by frenck** [comment]
Running Hass.io on macOS is not supported.

**Comment by alandtse** [comment]
@svh1985 While we can't run hassio natively in macOS, you can run it through a Linux virtual machine. There's a [Vagrant project](https://github.com/hassio-addons/hassio-vagrant).  This is how I test hassio for development on my mac.

**Comment by svh1985** [comment]
Perfect thanks for your help all!

**Comment by pvizeli** [comment]
I would suggest to use our virtual applicance from HassOS and run it inside a VM
