### ISSUE TITLE
Upgrade/Downgrade to specific version

### ISSUE THREAD

**Issue by TroLoos** [home-assistant/hassio-installer#70]
Is there any way to set the parameters in script to install HomeAssistant's specific version?

Sometimes new versions brake things, it would be great to be able to downgrade manually...

**Comment by frenck** [comment]
If you go into one of the Hass.io SSH add-ons, you can issue an upgrade command to a specific version, e.g.:

`hassio homeassistant upgrade --version=0.100.0`
