### ISSUE TITLE
Hassio causing UDP RcvbufErrors on port 5353

### ISSUE THREAD

**Issue by fatt0ny** [home-assistant/hassio-installer#71]
Hi,
After installing hassio (HA) & starting it, I began to receive multiple ipv4.udperrors 

Can anybody think of a reason why HA would be causing UDP errors

i have included an image of "netstat -ulpn" showing high Recv-Q of HA binding to port 5353

<img width="897" alt="Screenshot 2020-01-30 at 00 04 50" src="https://user-images.githubusercontent.com/4146903/73408461-352fcd00-42f4-11ea-8438-c48a9c19d296.png">

here is an image from netdata shoing the UDP errors whilst HA is running.
<img width="1208" alt="Screenshot 2020-01-30 at 00 20 17" src="https://user-images.githubusercontent.com/4146903/73409182-67422e80-42f6-11ea-9eb1-c169a222ab1c.png">

I would be very grateful if you could offer me any advice in tracking down the root cause of this!

Kind regards

**Comment by pvizeli** [comment]
maybe zeroconfig

**Comment by fatt0ny** [comment]
@pvizeli 
Thanks for you comment!

Do you mean a problem with zeroconf running in the HA container or on the host system?
