### ISSUE TITLE
"Unknown machine type aarch64" on install

### ISSUE THREAD

**Issue by Haarolean** [home-assistant/hassio-installer#73]
Hi,

got such an issue trying to install on pi4:

```
haarolean@piblack:[~]$ uname -m
aarch64
```
```
root@piblack:~# curl -sL https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh | bash -s
[Warning] No NetworkManager support on host.
[ERROR] Please set machine for aarch64
```
```
root@piblack:/opt/homeassistant# curl -sL https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh | bash -s -- -m aarch64
[Warning] No NetworkManager support on host.
[Error] Unknown machine type aarch64!
```

pi4-64 worked for me, but anywaysss

**Comment by frenck** [comment]
`aarch64` is not a valid machine time.

Please see the documentation for which are valid machine types:

<https://www.home-assistant.io/hassio/installation/#preparation>

**Comment by Haarolean** [comment]
What do you mean? That was supposed as an appropriate architecture in the
stdout output.
What's the point asking the user to set it if it's not supported?

чт, 6 февр. 2020 г., 10:49 Franck Nijhof <notifications@github.com>:

**Comment by frenck** [comment]
It asks you to define a machine type for architecture aarch64.
Machine types and architectures are not the same things.

Please check the linked documentation page for a list of machine types supported and accepted by the installer.
