### ISSUE TITLE
Machine type aarch64 not allowed

### ISSUE THREAD

**Issue by povlhp** [home-assistant/hassio-installer#74]
I will run hass.io on a TV box, quad core, 4GB RAM, 64-bit Armbian. 
Looking at the targets in the script, I can pick either qemuarm-64 or RaspberryPi4-64. 
There is no generic aarch64 machine. But the images to support is are here: https://hub.docker.com/u/homeassistant 

So I added aarch64 as an acceptable machine to the approved list - I assume it should be done so everybody can install on arm64 without pretending to be a Pi. Or is the Pi4-64 a better target to choose ?

Allowing and using machine type aarch64, I now run homeassistant/aarch64-homeassistant:0.105.2 with the pi4-64 target I was running this container:
 homeassistant/raspberrypi4-64-homeassistant:0.105.2

So seems there is an image for target machine = aarch64
```
if [[ ! "intel-nuc odroid-c2 odroid-n2 odroid-xu qemuarm qemuarm-64 qemux86 qemux86-64 raspberrypi raspberrypi2 raspberrypi3 raspberrypi4 raspberrypi3-64 raspberrypi4-64 tinker" = *"${MACHINE}"* ]]; then
    echo "[Error] Unknown machine type ${MACHINE}!"
    exit 1
fi
```

**Comment by frenck** [comment]
`qemuarm-64` is the generic machine version for the aarch64 architecture...

**Comment by povlhp** [comment]
Docs should be updated then to make it clear. And I really could not find anything telling me what the difference is. And why do the aarch64 version of homeassistabt docker image even exist ?

**Comment by frenck** [comment]
Machine types and architecture are not the same things.

aarch64 is used on Docker images that are not bound to a machine type, however, we do have images bound to a machine type to support specific machines better. (e.g., the Pi). However, that does not mean each image used on that machine uses a machine-specific version.

Feel free to open up a PR to our documentation if you thing improvements on that part is needed 👍
