### ISSUE TITLE
just one question

### ISSUE THREAD

**Issue by schluden** [home-assistant/hassio-installer#75]
How do I install a specific version with this hassio-installer?

**Comment by frenck** [comment]
Hi there @schluden!

During installation, you can't. After installation, you can downgrade the version of Home Assistant Core using the CLI that is available in e.g., the SSH add-on.

Please note, we use GitHub for tracking issues, not for providing support. If you have any further questions, please use or Discord Chat or Community Forums.

Thanks! 👍
