### ISSUE TITLE
How do I install the 0.91.4

### ISSUE THREAD

**Issue by cachenow** [home-assistant/hassio-installer#8]
I'm going to install the 0.91.4, but when I use the installer, I always get the latest version. How can I change hass.io version tag with the script?

**Comment by pvizeli** [comment]
`hassio ha update --version=0.91.4` on cli/ssh add-on

**Comment by cachenow** [comment]
> `hassio ha update --version=0.91.4` on cli/ssh add-on

Thanks @pvizeli , But I found 502 err when I installed the ssh add-on, then I used the docker ssh, it told me

/config # hassio ha update --version=0.91.4
**/bin/sh: hassio: not found**

that means I must be used the ssh add-on in hass.io web interface?

**Comment by cachenow** [comment]
and I used the Check Home Assistant configuration add-on to downgrade it, the messages said:

[Info] Start install HomeAssistant 0.91.4
You are using pip version 19.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[Info] Installed homeassistant==0.91.4, check config now
[Error] Wrong config found!
Testing configuration at /tmp/config
Failed config
  General Errors: 
    - Platform not found: tts.google_translate

Successful config (partial)

**Comment by cachenow** [comment]
@pvizeli Finally, If I'm going to do a fresh installation, how can I write the command with 0.91.4?

**Comment by cachenow** [comment]
@pvizeli hi, sorry to bother you again. could you help me for this case please?
