### ISSUE TITLE
Access denied for all addons using ingress 

### ISSUE THREAD

**Issue by barisdemirdelen** [home-assistant/hassio-installer#81]
I don't know if this is the correct place to ask this, but I have a system install with hassio-installer, and have some addons with homeassistant. With the supervisor, all ingress addons fails to open web ui with access denied messages.

For example influxdb log:

```
2020/02/22 00:38:01 [error] 661#661: *8 access forbidden by rule, client: 172.30.32.1, server: a0d7b954-influxdb, request: "GET / HTTP/1.1", host: "myhost.local", referrer: "https://myhost.local/hassio/ingress/a0d7b954_influxdb"
[22/Feb/2020:00:38:01 +0100] 403 192.168.1.142, 172.30.32.1(172.30.32.1) GET / HTTP/1.1 (Mozilla/5.0 (X11; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0)
```

Seeing these addons all have the following line in their nginx.conf:
`
allow 172.30.32.2;`

This is the ip for the supervisor. But the addons seems to be accessed from the host machine instead , with ip 172.30.32.1. This seems to be causing the access denied.

I am accessing the homeassistant via a reverse proxy to 172.30.32.1:8123

How is this supposed to work? Is this a configuration issue on my end?

**Comment by pvizeli** [comment]
> Is this a configuration issue on my end?

Yes, it is. Use the reverse proxy from the community addon or core. If you want to use our own solution, it needs a high knowledge about the system to make ingress working.

**Comment by barisdemirdelen** [comment]
Thanks for the reply, which addon exactly are you referring to? Is it the Nginx Home Assistant SSL Proxy or Nginx Proxy Manager?
