### ISSUE TITLE
How to uninstall hass.io docker containers

### ISSUE THREAD

**Issue by nicedevil007** [home-assistant/hassio-installer#84]
Hey guys,

I was using your script to install hass.io in a docker environment.
Now I want to uninstall it. If I just delete the 2 container inside portainer, they will automatically be recreated and started again.

I can't remove docker @ all because I have other services running!

Is there a script or a switch for the install script to achieve this?

**Comment by DanielsWrath** [comment]
from issue #42 

This really should be added somewhere. I have had multiple issues with this installer, and had to remove it a couple of times.

```
#bin/bash

#remove images (also prevents from restarting containers)
docker image rm $(docker image ls -aq)

#stop containers
docker container stop $(docker container ls -aq)

#remove containers
docker container rm $(docker container ls -aq)

#uninstall packages
sudo apt-get -y remove apparmor docker-ce

#cleanup some directories
```

You can also try `rm -f` if rm doesn't cut it.

**Comment by nicedevil007** [comment]
With this... Docker will be removed completly. So there is no way to remove hass.io without having to install the docker environment again o_O

**Comment by nicedevil007** [comment]
Ok did it like you said and just removed the steps with uninstalling docker and all other images.

So this were the steps to solve my problem:

```
#bin/bash

#remove the service
sudo systemctl stop hassio-supervisor.service
sudo systemctl disable hassio-supervisor.service
sudo systemctl disable hassio-apparmor.service
sudo systemctl daemon-reload
cd /etc/systemd/system
sudo rm hassio-*
```

after this I just opened portainer or maybe swarmpit (just what is installed to manage everything in webgui) and there I was able to remove all hass.io containers/images/volumes without them to restart by themself (because we stoped/disabled the systemd services).

So thank you :)

Not to forget this:

`sudo rm -R /usr/share/hassio`

**Comment by DanielsWrath** [comment]
If you don't want to remove docker you can run everything, except apt-get
