### ISSUE TITLE
arm64 issues

### ISSUE THREAD

**Issue by jasonehines** [home-assistant/hassio-installer#89]
I've got a Pi4 and the aarch64-hassio-dns container will not run. Also if you install with `-m raspberrypi4` but have the 64 bit kernel enabled, it installs the 64 bit containers instead of the the 32 bit containers. I've tested this on a fresh install of raspbian.

If I remove all the containers and services and set the kernel back to 32 bit and reinstall it works fine; only downside is I can't install Visual Studio Code addon.

**Comment by reesericci** [comment]
Same here but on a pi 3

**Comment by pvizeli** [comment]
> Ubuntu, Debian

We just support official this 2 OS. Raspbian is not a real debian. You can flush our 64bit rpi4 image and all work without issue 👍
